name: 'example'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+1'
repository: 'https://github.com/General-Developer/whisper_library'
homepage: 'https://www.youtube.com/@general_dev'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
funding:
  - 'https://github.com/sponsors/General-Developer'
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: 'flutter'
  cupertino_icons: '^1.0.8'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
flutter:
  uses-material-design: true
project:
  type: ''
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'