name: 'example'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+1'
repository: 'https://github.com/General-Developer/whisper_library'
homepage: 'https://www.youtube.com/@general_dev'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
funding:
  - 'https://github.com/sponsors/General-Developer'
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: 'flutter'
  cupertino_icons: '^1.0.8'
  general_lib: '^0.0.66'
  general_lib_flutter: '^0.0.41'
  packagex: '^0.0.85'
  simulate: '^0.0.52'
  general_framework: '^0.0.25'
  markdown_flutter: '^0.0.12'
  media_kit_fork: '^0.0.3'
  media_kit_libs_video_fork: '^0.0.2'
  media_kit_video_fork: '^0.0.2'
  path: '^1.9.0'
  general_system_device: '^0.0.51'
  general_audio: '^0.0.2'
  general_audio_flutter: '^0.0.2'
  whisper_library_dart: '^0.0.7'
  whisper_library_flutter: '^0.0.7'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
flutter:
  uses-material-design: true
project:
  type: ''
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
