rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/whisper_library_documentation/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_linux/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_fucshia/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_macos/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_server/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_apis/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_android/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_ios/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_client/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_scheme/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_dart/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_assets_flutter/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_web/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_flutter/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_isar_scheme/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_cli/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/whisper_library/package/whisper_library_windows/LICENSE
