name: 'whisper_library_flutter'
description: 'Whisper Is Library for transcribe sound wav AKA Speech To Text Or Extract Text From Audio'
version: '0.0.9'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
homepage: 'https://www.youtube.com/@general_dev'
repository: 'https://github.com/General-Developer/whisper_library'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
false_secrets:
  - 'android/jniLibs'
  - 'linux/'
  - 'windows/'
  - 'macos/'
  - 'ios/'
topics:
  - 'ggml'
  - 'artificial-intelligence'
  - 'machine-learning'
  - 'whisper'
  - 'speech-to-text'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: 'flutter'
dev_dependencies:
  flutter_lints: '^5.0.0'
  flutter_test:
    sdk: 'flutter'
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
dependency_overrides:
  mime: '^2.0.0'
  pointycastle: '^4.0.0'
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
