name: 'whisper_library_dart'
description: 'Whisper Is Library for transcribe sound wav AKA Speech To Text Or Extract Text From Audio'
version: '0.0.0'
homepage: 'https://www.youtube.com/@general_dev'
repository: 'https://github.com/General-Developer/whisper_library'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
funding:
  - 'https://github.com/sponsors/General-Developer'
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  path: '^1.9.0'
  collection: '^1.19.0'
  yaml: '^3.1.3'
  general_lib: '^0.0.64'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
executables:
  whisper_library: 'whisper_library'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
