name: 'whisper_library_dart'
description: 'Whisper Is Library for transcribe sound wav AKA Speech To Text Or Extract Text From Audio'
version: '0.0.7'
topics:
  - 'ggml'
  - 'artificial-intelligence'
  - 'machine-learning'
  - 'whisper'
  - 'speech-to-text'
environment:
  sdk: '>=3.7.0 <4.0.0'
dependencies:
  general_lib: '^0.0.66'
  ffi: '^2.1.0'
  path: '^1.9.0'
  general_ml: '^0.0.2'
  ffi_universe: '^0.0.4'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
  ffigen: '^15.0.0'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
flutter:
  uses-material-design: true
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
homepage: 'https://www.youtube.com/@general_dev'
repository: 'https://github.com/General-Developer/whisper_library'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
ffigen:
  name: 'WhisperLibrarySharedBindingsByGeneralDeveloper'
  description: 'GeneralAiSpeechToTextLibraryWhisper Binding By General Corporation & Global Corporation & General Developer'
  output: 'lib/ffi/bindings.dart'
  headers:
    entry-points:
      - '../../native_lib/lib/whisper.cpp/include/whisper.h'
      - '../../native_lib/lib/ggml/include/ggml.h'
      - '../../native_lib/lib/ggml/include/ggml-cpu.h'
      - '../../native_lib/lib/ggml/include/ggml-backend.h'
  compiler-opts:
    - '-I/usr/lib/clang/19.1.7/include'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
project:
  type: ''
